FROM ros:noetic-perception-focal

ENV DEBIAN_FRONTEND=noninteractive

RUN rm -f /etc/apt/sources.list.d/ros1-latest.list

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zip \
    nano \
    ptpd \
    lsb-release \
    python3-pip \
    libpcap-dev \
    libyaml-cpp-dev

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    apt-get update

RUN mkdir -p /catkin_ws/src

RUN apt-get update && apt-get install -y \
    ros-noetic-diagnostic-updater \
    ros-noetic-roslint \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/ros-drivers/velodyne /catkin_ws/src/velodyne && \
    cd /catkin_ws/src/velodyne && \
    git checkout master

COPY upd_angle_imu /catkin_ws/src/upd_angle_imu

RUN bash -c "source /opt/ros/noetic/setup.bash && cd /catkin_ws && catkin_make"


RUN pip3 install --upgrade pip && \
    pip3 install flask requests psutil gunicorn pyubx2 pyserial websockets asyncio

COPY webapp/ /webapp

EXPOSE 5000

WORKDIR /webapp	

CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "app:app"]
